-- Created by Vertabelo (http://vertabelo.com)
-- Last modification date: 2018-07-18 14:00:52.517

/* DROP DATABASE BD_PASAJE */


CREATE  DATABASE BD_PASAJE
GO

USE BD_PASAJE
GO

-- tables
-- Table: PASAJERO
CREATE TABLE PASAJERO (
    COD_PAS int IDENTITY(1,1) NOT NULL,
    NOM_PAS varchar(100)  NOT NULL,
    CONSTRAINT PASAJERO_pk PRIMARY KEY  (COD_PAS)
);

-- Table: RUTAS
CREATE TABLE RUTAS (
    COD_RUT int IDENTITY(1,1) NOT NULL,
    NOM_RUT varchar(100)  NOT NULL,
    COS_RUT decimal(5,2)  NOT NULL,
    CONSTRAINT RUTAS_pk PRIMARY KEY  (COD_RUT)
);

-- Table: VEHICULO
CREATE TABLE VEHICULO (
    COD_VEH int IDENTITY(1,1) NOT NULL,
    CAP_VEH int  NOT NULL,
    CONSTRAINT VEHICULO_pk PRIMARY KEY  (COD_VEH)
);

-- Table: VIAJE
CREATE TABLE VIAJE (
    COD_VIA int IDENTITY(1,1) NOT NULL,
    COD_VEH int  NOT NULL,
    COD_RUT int  NOT NULL,
    COD_PAS int  NOT NULL,
    CONSTRAINT VIAJE_pk PRIMARY KEY  (COD_VIA)
);

-- foreign keys
-- Reference: VIAJE_PASAJERO (table: VIAJE)
ALTER TABLE VIAJE ADD CONSTRAINT VIAJE_PASAJERO
    FOREIGN KEY (COD_PAS)
    REFERENCES PASAJERO (COD_PAS);

-- Reference: VIAJE_RUTAS (table: VIAJE)
ALTER TABLE VIAJE ADD CONSTRAINT VIAJE_RUTAS
    FOREIGN KEY (COD_RUT)
    REFERENCES RUTAS (COD_RUT);

-- Reference: VIAJE_VEHICULO (table: VIAJE)
ALTER TABLE VIAJE ADD CONSTRAINT VIAJE_VEHICULO
    FOREIGN KEY (COD_VEH)
    REFERENCES VEHICULO (COD_VEH);

-- End of file.