USE BD_PASAJE
GO

/* Muestra el vehículo con la que viajó el pasajero */
CREATE VIEW VW_PasRuta AS
SELECT PASAJERO.NOM_PAS AS 'Pasajero', VEHICULO.DES_VEH AS 'Vehículo'
FROM PASAJERO
INNER JOIN VIAJE ON VIAJE.COD_PAS = PASAJERO.COD_PAS
INNER JOIN VEHICULO ON VEHICULO.COD_VEH = VIAJE.COD_VEH
GO

SELECT * FROM VW_PasRuta
GO

/* Muestra las rutas donde ha viajado el pasajero y el costo de ellos */
CREATE VIEW VW_PasViaje AS
SELECT PASAJERO.NOM_PAS AS 'Pasajero', RUTAS.NOM_RUT AS 'Ruta', RUTAS.COS_RUT AS 'Costo'
FROM PASAJERO
INNER JOIN VIAJE ON VIAJE.COD_PAS = PASAJERO.COD_PAS
INNER JOIN RUTAS ON RUTAS.COD_RUT= VIAJE.COD_RUT
GO

SELECT * FROM VW_PasViaje
GO